### ISSUE TITLE
在复现过程中，我有一个问题

### ISSUE THREAD

**Issue by Fluffypp** [ColinLu50/Evade-GPT-Detector#1]
在执行test.py代码后生成的test_results/generated_text.tsv文件里，input和sico-output的内容对应不上？sico-output的内容均与Greece有关，应该对应squad下incontext.tsv的第一行。我的理解是input和sico-output的内容应该是对应的，不知道我的理解是否有误，还是在训练过程中出错，期望得到您的回复，感谢

**Comment by ColinLu50** [comment]
您好，请问是否能提供一下出现这个问题时所用的prompt文本，即`SICO_test_gen.py`中`final_prompt = prompt_constructor.get_final_prompt(feature, incontext_examples)` 所加载的prompt。有可能自动化过程中这个prompt包含了特定的指令，比如必须要包含Greece。

**Comment by Fluffypp** [comment]
您好！我后面打印了一下llm_input_list的前几行，发现选择的最佳特征一直是针对Greece的描述上，并且很冗长，所以我修改了一部分。这个问题应该是解决了，后面sicooutput的内容和input是对应的，您的工作对我的帮助很大，谢谢！！

**Comment by ColinLu50** [comment]
好的，很高兴帮助到你！
