### ISSUE TITLE
复现后无法绕过GPTZero检测

### ISSUE THREAD

**Issue by playerlt** [ColinLu50/Evade-GPT-Detector#2]
你好，想问一下现在训练结果是否还可以通过GPTZero的检测

**Comment by ColinLu50** [comment]
您好，感谢您关注我们的工作。我们关于GPTZero的实验是在2023年5月做的，到现在一年多的时间该检测器可能发生了较大的变化，甚至可能针对我们的工作进行了优化（这也是我们发表该工作的初衷）。

如果您想检验该方法对GPTZero是否有效，最直接的办法就是使用GPTZero API作为代理检测器训练。希望能够帮助到您。

**Comment by playerlt** [comment]
> 您好，感谢您关注我们的工作。我们关于GPTZero的实验是在2023年5月做的，到现在一年多的时间该检测器可能发生了较大的变化，甚至可能针对我们的工作进行了优化（这也是我们发表该工作的初衷）。
> 
> 如果您想检验该方法对GPTZero是否有效，最直接的办法就是使用GPTZero API作为代理检测器训练。希望能够帮助到您。

感谢回复！
